name: debug

on:
  pull_request:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:
      - id: dump
        run: |
          echo "REF ${{ github.ref }}"
          echo "REF_NAME ${{ github.ref_name }}"
          echo "HEAD_REF ${{github.head_ref}}"
          cat <<"EOF"
          ${{ toJSON(github.event) }}
          EOF
          echo "${{github.event.pull_request}}"
